feat(thirdparty): use official rocksdb
apache/incubator-pegasus pull request #1048
Opened 2022-07-12 14:44 UTC by acelyc111

https://github.com/apache/incubator-pegasus/issues/1047

2022-07-12 15:15 UTC, acelyc111 commented on rdsn/thirdparty/CMakeLists.txt
> +        https://github.com/facebook/rocksdb/archive/refs/tags/v6.6.4.tar.gz
```suggestion
        URL https://github.com/facebook/rocksdb/archive/refs/tags/v6.6.4.tar.gz
```

2022-07-14 09:54 UTC, levy5307 submitted a review, later dismissed

2022-07-14 09:57 UTC, foreverneverer requested changes
hope block merge before release 2.4

2022-07-14 10:04 UTC, levy5307 commented
> hope block merge before release 2.4

Better to convert it to draft :)

2022-09-27 16:21 UTC, acelyc111 commented
> hope block merge before release 2.4

@foreverneverer Since we have created an separete branch v2.4 for releasing 2.4.0, so could we continue this work?

2022-11-08 12:40 UTC, foreverneverer approved these changes

2022-11-08 12:50 UTC, empiredan approved these changes

2022-11-08 15:50 UTC, merged